name: ntk_map_view
description: "A crossplatform map view for flutter based on leaflet"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1
  latlong2: ^0.9.0
  universal_html: ^2.2.4
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/
    - assets/map.html